### ISSUE TITLE
Header and frame offer different multiplicity 

### ISSUE THREAD

**Issue by LPardue** [martinthomson/alt-svcb#11]
The header allows an arbitrary number of alternativess per request. The frame only allows one alternative per origin (and only the last one). I don't see much technical reason for this asymmetry. It could be easily resolved by changing one of them (e.g. allowing the frame to carry a comma-separated list of values). Failing that, we could explain why they are different a bit more.

**Comment by martinthomson** [comment]
My initial take here is that one should be plenty and we only allow more than that for a field because we can't really stop people from adding multiple there.  I'd prefer to explain that and be done with it.

**Comment by LPardue** [comment]
Supporting only 1 would work for me, In other specs I've seen what want an Item singleton, they try to accomodate it by saying that any concatenation would look like a list, which is the wrong type and would fail to be parsed - failing closed in this case.

**Comment by martinthomson** [comment]
Yeah, I don't think that we need to fail closed here.  Using SF means that we are outsourcing most of the parsing pieces already, so if we get N, then any one of those N should work.  If not then ¯\\(°\_o)/¯.  Potential for harm is minimal.
